CREATE DATABASE ECOMZ;

CREATE TABLE PRODUCTS (
      PRODUCT_ID int PRIMARY KEY,
      PRODUCT_NAME VARCHAR(25),
      PRICE FLOAT(5, 2)
);

SELECT * FROM PRODUCTS;
INSERT INTO PRODUCTS VALUES(4,'You are the Placebo',10);
INSERT INTO PRODUCTS VALUES(5,'START WITH WHY',15);
