CREATE DATABASE TEST;
-- DISPLAY ALL THE DATABASES
SHOW DATABASES;
-- SWITCH TO THE DB
USE SAKILA;

-- FETCH STATIC VALUES
SELECT 'THURSDAY';
-- USER DEFINED COLUMN NAME
SELECT 'THURSDAY' AS 'DAY';

SELECT 100+200;
SELECT 100+200 AS TOTAL;

-- SCALAR FUNCTIONS
SELECT PI();
SELECT MOD(45,7);
SELECT SQRT(25);

-- SELECTING DATA FROM THE TABLES
SELECT * FROM ACTOR;
SELECT * FROM ACTOR
ORDER BY FIRST_NAME;
SELECT * FROM ACTOR
ORDER BY FIRST_NAME ASC;
SELECT * FROM ACTOR
ORDER BY FIRST_NAME DESC;
SELECT * FROM ACTOR
ORDER BY 3;
SELECT * FROM ACTOR
ORDER BY 3 DESC;

-- FILTERING ROWS
SELECT * FROM ACTOR WHERE ACTOR_ID < 6;
SELECT * FROM ACTOR WHERE LAST_NAME = 'GUINESS';

-- MULTI COLUMN SORT
SELECT * FROM ACTOR ORDER BY FIRST_NAME;
SELECT * FROM ACTOR ORDER BY FIRST_NAME ASC, LAST_NAME DESC;
-- INSTANT PRACTICE.
-- SORT THE ACTORS BY LAST_NAME ASC AND FIRST NAME DESCENDING USING THE COLUMN INDEX.
select * from ACTOR order by 3 ASC,2 DESC;

SELECT * FROM ACTOR WHERE FALSE;
SELECT * FROM ACTOR WHERE TRUE;
SELECT * FROM ACTOR WHERE 1 = 1;
SELECT * FROM ACTOR WHERE 1 = 2;

-- COUNT AGGREGATE FUNCTION
SELECT COUNT(*) FROM ACTOR;
-- INSTANT PRACTICE
-- SAM, A DATABASE DEVELOPER WOULD LIKE TO DISPLAY THE DETAILS OF ACTORS.
-- DISPLAY ALL THE COLUMNS IN THE SAME ORDER
-- return_date should be  'DATE OF RETURN' , inventory_id should be 'INVENTORY'.

SELECT rental_id, rental_date, inventory_id AS INVENTORY, customer_id, return_date AS 'DATE OF RETURN', 
staff_id, last_update FROM RENTAL;
SELECT * FROM RENTAL;

SELECT  1, 2, 3 AS 'INVENTORY', 4, 5 AS 'DATE OF RETURN', 6, 7 FROM RENTAL;  
SELECT * FROM PAYMENT;
SELECT AMOUNT, ROUND(AMOUNT) FROM PAYMENT;
SELECT ROUND(8.45) FROM PAYMENT;
SELECT ROUND(8.5) FROM PAYMENT;
SELECT ROUND(-14.33);
SELECT ROUND(1.234, 0);
SELECT ROUND(-14.73);
SELECT ROUND(1.234, 1);
-- PREDICT THE OUTPUT
-- MISTAKE 123.00
SELECT ROUND(1234.567, -1);
SELECT ROUND(1256.567, -2) AS 'ROUNED VALUE';

SELECT AMOUNT FROM PAYMENT;
SELECT ROUND(AMOUNT), ROUND(AMOUNT,0), ROUND(AMOUNT,1) FROM PAYMENT;
SELECT FLOOR(1.2);   
SELECT CEILING(1.2);
-- PREDICT 
SELECT FLOOR(-1.2);   -- -2 ..... -1
SELECT CEILING (-1.2);

-- STRING OPERATIONS

-- THE BELOW ARE ARITHMETIC AND NO CONCATENATION HAPPENS
SELECT 1 + 1 AS 'ADD';
SELECT '1' + '1' AS 'ADD';
SELECT '1A' + '1' AS 'ADD';
SELECT '1A' + 'B' AS 'ADD';
SELECT 'A2' + '1' AS 'ADD';
SELECT 'A2' + '2' AS 'ADD';
SELECT 'A2' + 'A2' AS 'ADD';

SELECT CONCAT(1,1) AS 'CONCATENATE';
SELECT CONCAT('1','1') AS 'CONCATENATE';
SELECT CONCAT('A2', '2') AS 'CONCATENATE';
SELECT CONCAT('RED',  ' GREEN', ' BLUE') AS 'COLORS';
SELECT * FROM ACTOR;
-- IP
-- FORMAT ACTOR_ID, 'FULL NAME' 
-- FIRST NAME : ED LAST NAME : CHASE
-- RESULT : 3, FIRST NAME : ED LAST NAME : CHASE 
SELECT ACTOR_ID, CONCAT('FIRST_NAME : ', FIRST_NAME , ' LAST NAME : ', LAST_NAME) AS 'FULL NAME' FROM ACTOR;

SELECT LOWER(FIRST_NAME) FROM ACTOR;
SELECT UPPER(FIRST_NAME) FROM ACTOR;
SELECT LEFT(FIRST_NAME,2) FROM ACTOR;
SELECT LOWER(LEFT(FIRST_NAME,2)) FROM ACTOR;

SELECT * FROM ACTOR;
-- IP
-- 'REVERSE FULL NAME'
-- ESAHC DE
SELECT CONCAT(REVERSE(LAST_NAME),' ', REVERSE(FIRST_NAME)) FROM ACTOR;
Select REVERSE(CONCAT(FIRST_NAME,' ',LAST_NAME)) AS 'REVERSE FULL NAME' FROM ACTOR;

-- IP
--  'NAME WITH INTIAL'
--  GRANT.A
--  GARLAND.A
SELECT CONCAT(last_name, '.' ,left(First_name,1)) As 'name with initial' from actor;
SELECT REVERSE(FIRST_NAME) FROM ACTOR;

-- SELECT LAST UPDATE FROM ACTOR;
SELECT LAST_UPDATE FROM ACTOR;
SELECT DATE_FORMAT(LAST_UPDATE,'%m/%d/%y') AS 'LAST UPDATE' FROM ACTOR;
SELECT DATE_FORMAT(LAST_UPDATE,'%m-%d-%y') AS 'LAST UPDATE' FROM ACTOR;
SELECT WEEK(LAST_UPDATE) FROM ACTOR;
SELECT (PAYMENT_DATE) FROM PAYMENT;

-- IP
-- DAYOFWEEK, NAMEOFMONTH, QUARTER
-- PAYMENT_DATE (PAYMENT)