USE TEST;

-- DDL (DATA DEFINITION LANGUAGE)
-- CREATE THE STRUCTURES (CREATE TABLE, COLUMNS AND SPECIFY THE DATA TYPE)
-- THE UNIQUE CONSTRAINT
CREATE TABLE BOOKS
(
	BOOK_ID VARCHAR(15) UNIQUE
);
-- ALLOWS ONE OR MORE NULL VALUES
-- DOES NOT ALLOW DUPLICATES
-- MORE THAN ONE UNIQUE CONSTRAINT CAN BE THERE IN A TABLE
INSERT INTO BOOKS VALUES(NULL);
INSERT INTO BOOKS VALUES('TEST');
INSERT INTO BOOKS VALUES(NULL);
INSERT INTO BOOKS VALUES('TEST');
SELECT * FROM BOOKS;
SELECT * FROM BOOKS1;
DELETE FROM BOOKS1;
CREATE TABLE BOOKS1
(
	BOOK_ID VARCHAR(15) UNIQUE,
    BOOK_NAME VARCHAR(15) UNIQUE
);
-- IP identify the queries that will be successful 
INSERT INTO BOOKS1 VALUES ('test', 'test1');
INSERT INTO BOOKS1 VALUES ('test', 'test2');
INSERT INTO BOOKS1 VALUES ('test1', 'test1');
INSERT INTO BOOKS1 VALUES ('test2', 'test2');

-- PRIMARY KEY (NO NULL, NO DUPLIATES)
CREATE TABLE BOOKS2
(
	BOOK_ID VARCHAR(15) PRIMARY KEY
);
-- IDENTIFY THE ROWS THAT WILL GET INSERTED
INSERT INTO BOOKS2 VALUES(NULL);
INSERT INTO BOOKS2 VALUES('TEST');
INSERT INTO BOOKS2 VALUES(NULL);
INSERT INTO BOOKS2 VALUES('TEST');

CREATE TABLE BOOKS3
(
--  MULTIPLE PRIMARY KEYS ARE NOT ALLOWED
	BOOK_ID VARCHAR(15) PRIMARY KEY,
    BOOK_NAME VARCHAR(15) PRIMARY KEY
);

-- CHECK CONSTRAINT - DOMAIN INTEGRITY
CREATE TABLE COUNTRIES (
C_ID CHAR(5) NOT NULL,
C_NAME VARCHAR(25) NOT NULL CHECK (C_NAME IN ('SP','IN','UK'))
);
-- PREDICT
INSERT INTO COUNTRIES VALUES (NULL, 'SP');
INSERT INTO COUNTRIES VALUES (1, 'SP');
INSERT INTO COUNTRIES VALUES (1, 'NZ');
INSERT INTO COUNTRIES VALUES (1, NULL);
INSERT INTO COUNTRIES VALUES (NULL, NULL);